# PyInstaller spec for Yaffo — a macOS .app bundle.
#
# Build:  pyinstaller --noconfirm yaffo.spec   (packaging/build_dmg.sh does this)
#
# The task system is multi-process (a host that spawns workers). PyInstaller's
# multiprocessing support + multiprocessing.freeze_support() in yaffo/__main__.py
# make that work: a spawned worker re-execs this frozen binary and the bootloader
# runs the worker instead of the app.
import os

from PyInstaller.utils.hooks import collect_all, collect_submodules

# Generated by packaging/make_icons.sh from the app SVG (absent on a bare run).
ICON = "packaging/icon.icns" if os.path.exists("packaging/icon.icns") else None

# Version comes from the VERSION file (bumped by packaging/bump_version.py).
APP_VERSION = open("VERSION").read().strip() if os.path.exists("VERSION") else "0.0.0"

datas = []
binaries = []
hiddenimports = []

# Native / data-heavy packages PyInstaller can't fully trace on its own (scipy
# ships Cython helpers like scipy._cyutility that the default hook misses; rumps
# pulls in pyobjc for the menu-bar item).
for pkg in ("onnxruntime", "insightface", "cv2", "pillow_heif", "scipy", "rumps"):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# Pull in dynamically-imported submodules: our own package (routes/tasks/automations
# are imported by name at runtime), sklearn (clustering), and explicit stragglers.
hiddenimports += collect_submodules("yaffo")
hiddenimports += collect_submodules("sklearn")
hiddenimports += ["starlark", "keyring.backends.macOS", "waitress",
                  "objc", "Foundation", "AppKit", "PyObjCTools"]

# Non-.py data shipped inside the yaffo package. Listed explicitly as source-tree
# dirs: collect_data_files() silently drops these because yaffo is our own source
# package (on pathex, not pip-installed), so PyInstaller treats its files as source.
datas += [
    ("yaffo/templates", "yaffo/templates"),
    ("yaffo/static", "yaffo/static"),
    ("yaffo/translations", "yaffo/translations"),
    ("yaffo/utils/clip_tokenizer", "yaffo/utils/clip_tokenizer"),  # vendored CLIP vocab .gz
    ("yaffo/scripts/db/migrations", "yaffo/scripts/db/migrations"),  # loaded by file path
    ("resources", "resources"),  # UI resources + THIRD_PARTY_LICENSES
]

a = Analysis(
    ["yaffo/__main__.py"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "PyQt5", "PyQt6", "PySide2", "PySide6"],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Yaffo Photo Organizer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    target_arch="arm64",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Yaffo Photo Organizer",
)

app = BUNDLE(
    coll,
    name="Yaffo Photo Organizer.app",
    icon=ICON,
    bundle_identifier="com.jasonturan.yaffo",
    version=APP_VERSION,
    info_plist={
        "CFBundleName": "Yaffo Photo Organizer",
        "CFBundleDisplayName": "Yaffo Photo Organizer",
        "CFBundleShortVersionString": APP_VERSION,
        "CFBundleVersion": APP_VERSION,
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "14.0",
        # Menu-bar agent: live in the menu bar, no Dock icon / Cmd-Tab entry.
        "LSUIElement": True,
    },
)
