"""Publish the application's design tokens into the documentation build.

docs/stylesheets/extra.css maps Material's --md-* variables onto Yaffo's own
--color-*/--radius-*/--shadow-* tokens, so the documentation palette tracks the
app instead of restating it. MkDocs only publishes files underneath docs_dir,
though, so those token files cannot simply be @imported from yaffo/static —
this hook copies them into the build instead.

Both files are pure custom-property declarations (the drift guard in
tests/yaffo/test_design_tokens.py keeps them that way), so importing them
defines variables and styles nothing on its own.
"""

from __future__ import annotations

from pathlib import Path

from mkdocs.config.defaults import MkDocsConfig
from mkdocs.exceptions import PluginError
from mkdocs.structure.files import Files, File

ROOT = Path(__file__).resolve().parent.parent
STATIC = ROOT / "yaffo" / "static"

# The docs' dark scheme is Material's "slate", not the app's [data-theme] hook,
# so darkroom's block is re-scoped on the way in. Rewriting the selector here
# rather than hand-maintaining a copy is the whole point: the values stay in the
# app's file. If the app ever renames the attribute, the build fails loudly
# instead of silently publishing a dark theme that never activates.
DARKROOM_SELECTOR = '[data-theme="darkroom"]'
SLATE_SELECTOR = '[data-md-color-scheme="slate"]'

BANNER = (
    "/* Generated by hooks/design_tokens.py from {source}.\n"
    " * Do not edit: change the token in the application instead. */\n"
)

# (published path, source file, optional selector rewrite)
SOURCES: list[tuple[str, Path, tuple[str, str] | None]] = [
    ("stylesheets/yaffo-tokens.css", STATIC / "tokens.css", None),
    (
        "stylesheets/yaffo-tokens-darkroom.css",
        STATIC / "themes" / "darkroom" / "tokens.css",
        (DARKROOM_SELECTOR, SLATE_SELECTOR),
    ),
]


def on_files(files: Files, config: MkDocsConfig) -> Files:
    for src_uri, source, rewrite in SOURCES:
        if not source.is_file():
            raise PluginError(f"design token source is missing: {source}")

        text = source.read_text()
        if rewrite is not None:
            old, new = rewrite
            if old not in text:
                raise PluginError(
                    f"{source} no longer contains the selector {old!r}; "
                    f"update SOURCES in {Path(__file__).name}"
                )
            text = text.replace(old, new)

        banner = BANNER.format(source=source.relative_to(ROOT).as_posix())
        files.append(File.generated(config, src_uri, content=banner + text))

    return files
